[theme]
base = "dark"
primaryColor = "#1976D2"              # Strong blue for highlights/buttons
backgroundColor = "#16213E"           # Deep, rich dark blue for main background
secondaryBackgroundColor = "#1A1A2E"  # Slightly lighter dark blue for cards/sidebars
textColor = "#F5F6FA"                 # Very light for contrast
font = "sans serif"