[theme]
base = "dark"
primaryColor = "#1976D2"              # Strong blue for highlights/buttons
backgroundColor = "#0D1B2A"           # Deep dark blue for main background
secondaryBackgroundColor = "#1B263B"  # Slightly lighter dark blue for cards/sidebars
textColor = "#F5F6FA"                 # Very light for contrast
font = "sans serif"